name: "Ubuntu"
on: [ "push", "pull_request" ]

concurrency:
  group: ${{github.workflow}}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v4
      with:
        python-version: 3.8

    - name: Run tests
      run: |
        sudo apt-get update
        sudo apt-get install libxml2-dev libxslt-dev
        pip install -U poetry tox
        tox

    - name: Upload coverage reports to Codecov
      uses: codecov/codecov-action@v4.0.1
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        slug: shengchenyang/FontMapster
